/**
 * PrimePicks Store - Catálogo de Produtos
 */

const PRODUCTS_DATA = [
  {
    id: 1,
    title: "Fone de Ouvido Noise Cancelling Pro ANC",
    category: "audio",
    categoryName: "Áudio & Som",
    price: 489.90,
    oldPrice: 799.00,
    rating: 4.9,
    reviewsCount: 342,
    badge: "Mais Vendido",
    badgeType: "hot",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
    description: "Cancelamento ativo de ruído híbrido avançado, drivers de 40mm de alta fidelidade e bateria com autonomia de até 60 horas.",
    specs: ["Bateria 60h", "Bluetooth 5.3", "Áudio Hi-Res", "Microfone Duplo"],
    featured: true,
    inStock: true
  },
  {
    id: 2,
    title: "Smartwatch Ultra Titanium Series 9",
    category: "wearables",
    categoryName: "Smartwatches",
    price: 359.00,
    oldPrice: 599.00,
    rating: 4.8,
    reviewsCount: 215,
    badge: "Destaque",
    badgeType: "prime",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    description: "Caixa em titânio resistente a impactos, tela AMOLED Always-on de 2.0 polegadas, monitoramento cardíaco, oxigenação e GPS integrado.",
    specs: ["Tela AMOLED 2.0\"", "À Prova D'água 5ATM", "GPS Integrado", "NFC Pagamentos"],
    featured: true,
    inStock: true
  },
  {
    id: 3,
    title: "Teclado Mecânico Compacto Wireless RGB",
    category: "setup",
    categoryName: "Setup & Produtividade",
    price: 279.90,
    oldPrice: 429.00,
    rating: 4.9,
    reviewsCount: 188,
    badge: "35% OFF",
    badgeType: "sale",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80",
    description: "Switches mecânicos hot-swappable lineares, iluminação RGB personalizável por tecla e triplo modo de conexão (2.4Ghz, Bluetooth e Cabo).",
    specs: ["Switches Hot-Swap", "Bateria 4000mAh", "Conexão Tri-mode", "Estrutura Gasket"],
    featured: true,
    inStock: true
  },
  {
    id: 4,
    title: "Lâmpada Inteligente RGB Smart Light Bar",
    category: "casa",
    categoryName: "Casa Inteligente",
    price: 159.00,
    oldPrice: 249.90,
    rating: 4.7,
    reviewsCount: 96,
    badge: "Novidade",
    badgeType: "new",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80",
    description: "Barra de iluminação ambiente para monitores com sincronização de áudio, 16 milhões de cores e controle total via App e assistentes de voz.",
    specs: ["16 Milhões de Cores", "Sincronia Musical", "Compatível com Alexa/Google", "Fácil Instalação"],
    featured: false,
    inStock: true
  },
  {
    id: 5,
    title: "Mouse Ergonômico Sem Fio Precision Master",
    category: "setup",
    categoryName: "Setup & Produtividade",
    price: 219.00,
    oldPrice: 319.00,
    rating: 4.8,
    reviewsCount: 142,
    badge: "Ergonomia",
    badgeType: "prime",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80",
    description: "Design anatômico que previne fadiga por esforço repetitivo, sensor óptico de alta precisão 4000 DPI e cliques ultra silenciosos.",
    specs: ["Sensor 4000 DPI", "Clique Silencioso", "Bateria Recarregável", "Multi-dispositivo"],
    featured: false,
    inStock: true
  },
  {
    id: 6,
    title: "Carregador Magnético 3 em 1 Fast Wireless",
    category: "acessorios",
    categoryName: "Acessórios",
    price: 189.90,
    oldPrice: 289.00,
    rating: 4.9,
    reviewsCount: 308,
    badge: "Top Escolha",
    badgeType: "hot",
    image: "https://images.unsplash.com/photo-1622445262464-84b1456045b6?auto=format&fit=crop&w=800&q=80",
    description: "Estação de carregamento por indução rápida 15W para Smartphone, Smartwatch e Fones de ouvido simultaneamente. Design dobrável e compacto.",
    specs: ["Potência 15W Fast", "Compatível MagSafe", "Proteção Térmica", "Estrutura de Alumínio"],
    featured: true,
    inStock: true
  },
  {
    id: 7,
    title: "Mochila Executiva Impermeável Antifurto",
    category: "lifestyle",
    categoryName: "Lifestyle & Estilo",
    price: 249.00,
    oldPrice: 389.00,
    rating: 4.8,
    reviewsCount: 175,
    badge: "Impermeável",
    badgeType: "new",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80",
    description: "Compartimento acolchoado para notebook de até 16 polegadas, tecido resistente à água, cadeado integrado e porta USB externa.",
    specs: ["Para Laptops 16\"", "Zíperes Antifurto", "Porta USB Integrada", "Costas Respiráveis"],
    featured: false,
    inStock: true
  },
  {
    id: 8,
    title: "Caixa de Som Portátil SoundBoom Waterproof",
    category: "audio",
    categoryName: "Áudio & Som",
    price: 319.90,
    oldPrice: 499.00,
    rating: 4.9,
    reviewsCount: 260,
    badge: "IPX7 Prova d'água",
    badgeType: "hot",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80",
    description: "Graves potentes com radiadores passivos duplos, certificação IPX7 totalmente à prova de água e até 24 horas de reprodução contínua.",
    specs: ["Proteção IPX7", "Som 360 Graus", "24h de Autonomia", "Função Powerbank"],
    featured: true,
    inStock: true
  }
];

const CATEGORIES = [
  { id: "all", name: "Todos os Produtos", icon: "grid" },
  { id: "audio", name: "Áudio & Som", icon: "headphones" },
  { id: "wearables", name: "Smartwatches", icon: "watch" },
  { id: "setup", name: "Setup & Trabalho", icon: "monitor" },
  { id: "casa", name: "Casa Inteligente", icon: "home" },
  { id: "acessorios", name: "Acessórios", icon: "zap" },
  { id: "lifestyle", name: "Estilo & Viagem", icon: "briefcase" }
];
